const DISCOUNT_BILL_ON_100 = 5;
const DISCOUNT_BY_USER = {
    IS_AN_EMPLOYEE: 30,
    IS_AN_AFFILIATE: 10,
    IS_CUSTOMER_FOR_OVER_2_YEAS: 5,
    ON_GROCERIES: 0
}
module.exports = {
    DISCOUNT_BILL_ON_100,
    DISCOUNT_BY_USER
}